# This file was generated by nvfetcher, please do not modify it manually.
{fetchFromGitHub}: {
  bang-bang = {
    pname = "bang-bang";
    version = "ec991b80ba7d4dda7a962167b036efc5c2d79419";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-bang-bang";
      rev = "ec991b80ba7d4dda7a962167b036efc5c2d79419";
      fetchSubmodules = false;
      sha256 = "sha256-oPPCtFN2DPuM//c48SXb4TrFRjJtccg0YPXcAo0Lxq0=";
    };
    date = "2023-07-23";
  };
  git-abbr = {
    pname = "git-abbr";
    version = "faa3d2581b800c45960e8cd5087ff09acb936b85";
    src = fetchFromGitHub {
      owner = "pupbrained";
      repo = "fish-git-abbr";
      rev = "faa3d2581b800c45960e8cd5087ff09acb936b85";
      fetchSubmodules = false;
      sha256 = "sha256-8gxqYGN9XIlX1cZovX6r5zo8C8hOrsYIVN39oVGbWv0=";
    };
    date = "2024-08-14";
  };
  gityaw = {
    pname = "gityaw";
    version = "59196560e0f4520db63fb8cab645510377bb8b13";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-gityaw";
      rev = "59196560e0f4520db63fb8cab645510377bb8b13";
      fetchSubmodules = false;
      sha256 = "sha256-STXNxSsjSopB+lbB4hEYdhJifRfsImRwbZ1SxwEhkuM=";
    };
    date = "2019-01-07";
  };
  jj-abbr = {
    pname = "jj-abbr";
    version = "bc4968b588fc0cc2f3c1f9459195c5b0184fe2ca";
    src = fetchFromGitHub {
      owner = "pupbrained";
      repo = "plugin-jj";
      rev = "bc4968b588fc0cc2f3c1f9459195c5b0184fe2ca";
      fetchSubmodules = false;
      sha256 = "sha256-snyE3yvbpQ0nwI+JRff7cQRidVr3wwU4CIGDMMbUGwg=";
    };
    date = "2025-07-25";
  };
  license = {
    pname = "license";
    version = "0155b16f102957ec0c734a90979245dc1073f979";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-license";
      rev = "0155b16f102957ec0c734a90979245dc1073f979";
      fetchSubmodules = false;
      sha256 = "sha256-Bi9Q5rekZoyXYbRV+U4SmwCdqCl0pFupzm5si7SxFns=";
    };
    date = "2018-10-22";
  };
  replay-fish = {
    pname = "replay-fish";
    version = "d2ecacd3fe7126e822ce8918389f3ad93b14c86c";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "replay.fish";
      rev = "d2ecacd3fe7126e822ce8918389f3ad93b14c86c";
      fetchSubmodules = false;
      sha256 = "sha256-TzQ97h9tBRUg+A7DSKeTBWLQuThicbu19DHMwkmUXdg=";
    };
    date = "2024-07-01";
  };
  wttr = {
    pname = "wttr";
    version = "7500e382e6b29a463edc57598217ce0cfaf8c90c";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-wttr";
      rev = "7500e382e6b29a463edc57598217ce0cfaf8c90c";
      fetchSubmodules = false;
      sha256 = "sha256-k3FrRPxKCiObO6HgtDx8ORbcLmfSYQsQeq5SAoNfZbE=";
    };
    date = "2016-05-23";
  };
}
