[options]
minecraft = "1.21.11"
loader = "fabric"

[mods]
abridged = "*"
almanac = "*"
alternate-current = "*"
appleskin = "*"
architectury-api = "*"
balm = "*"
c2me-fabric = "*"
cloth-config = "21.11.153+fabric"
clumps = "*"
collective = "*"
configmanager = "1.1.1"
controlify = "2.5.2"
cristel-lib = "*"
debugify = "1.21.11+1.0"
double-doors = "*"
fabric-api = "0.141.3+1.21.11"
fabric-language-kotlin = "1.13.9+kotlin.2.3.10"
fallingtree = "*"
ferrite-core = "8.2.0-fabric"
forge-config-api-port = "21.11.1"
forgiving-void = "*"
geophilic = "*"
immersive-winds = "*"
inventory-totem = "*"
jade = "*"
jamlib = "*"
leaves-be-gone = "*"
lithium = "mc1.21.11-0.21.3-fabric"
lmd = "*"
lmft = "*"
lootr = "*"
mes-moogs-end-structures = "*"
mixintrace = "1.1.1+1.17"
mns-moogs-nether-structures = "*"
moogs-structure-lib = "*"
moogs-voyager-structures = "*"
mru = "*"
mss-moogs-soaring-structures = "*"
netherportalfix = "*"
no-chat-reports = "Fabric-1.21.11-v2.18.0"
notenoughcrashes = "*"
polymer = "*"
puzzles-lib = "*"
rightclickharvest = "*"
silk = "*"
snow-under-trees-remastered = "*"
sort-it-out = "*"
threadtweak = "*"
towns-and-towers = "*"
universal-graves = "*"
veinminer = "*"
waystones = "*"
yacl = "3.8.2+1.21.11-fabric"
