creation_rules:
  - path_regex: (^|.*/)navis\.yaml
    age:
      # admin (shared root ssh key, used for editing)
      - age12dcp6djv4ly6p9kn33e6w22rtax7nempxusuvfw2209f0xz5fg8qfauynz
      # navis host key (/etc/ssh/ssh_host_ed25519_key)
      - age18nfmm4wn4ewxe2lq4nx5mumr8ldep7q2ykgnyfpkv3dxjq825ugqtspc9d
  - path_regex: (^|.*/)polaris\.yaml
    age:
      # admin (shared root ssh key, used for editing)
      - age12dcp6djv4ly6p9kn33e6w22rtax7nempxusuvfw2209f0xz5fg8qfauynz
      # polaris host key (/etc/ssh/ssh_host_ed25519_key)
      - age16d4thm55e0xgrereg94rumxe932gfh7mmrsavptzpe8t3ludd3jslymp86
