creation_rules:
  - path_regex: (^|.*/)navis\.yaml
    age: "age12dcp6djv4ly6p9kn33e6w22rtax7nempxusuvfw2209f0xz5fg8qfauynz"
  - path_regex: (^|.*/)polaris\.yaml
    age: "age12dcp6djv4ly6p9kn33e6w22rtax7nempxusuvfw2209f0xz5fg8qfauynz"
